def export_questions_to_latex_simple(questions: List[Dict]) -> str:
    """問題リストを超シンプルLaTeX形式で出力（最小構成で確実にコンパイル）"""
    
    latex_content = r"""
\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[top=25mm,bottom=25mm,left=20mm,right=20mm]{geometry}

\title{歯科国家試験問題集}
\author{Generated by Dental DX PoC}
\date{\today}

\begin{document}
\maketitle

"""
    
    for i, q in enumerate(questions, 1):
        q_num = q.get("number", f"Q{i}")
        question_text = q.get("question", "").replace("&", "\\&").replace("%", "\\%").replace("$", "\\$").replace("#", "\\#").replace("_", "\\_").replace("{", "\\{").replace("}", "\\}")
        choices = q.get("choices", [])
        answer = q.get("answer", "")
        subject = q.get("subject", "").replace("&", "\\&").replace("%", "\\%").replace("$", "\\$").replace("#", "\\#").replace("_", "\\_").replace("{", "\\{").replace("}", "\\}")
        
        latex_content += f"""
\\section{{問題 {q_num}}}
\\textbf{{科目:}} {subject}

\\textbf{{問題:}}
{question_text}

"""
        
        # 選択肢の処理
        if choices:
            # 選択肢が文字列の場合（A. choice | B. choice 形式）
            if isinstance(choices, str):
                latex_content += "\\textbf{選択肢:}\n\n"
                choice_parts = choices.split(" | ")
                for choice in choice_parts:
                    if ". " in choice:
                        choice_text = choice.split(". ", 1)[1].strip()
                        escaped_choice = choice_text.replace("&", "\\&").replace("%", "\\%").replace("$", "\\$").replace("#", "\\#").replace("_", "\\_").replace("{", "\\{").replace("}", "\\}")
                        latex_content += f"{choice}\n\n"
                latex_content += "\n"
            
            # 選択肢が配列の場合
            elif isinstance(choices, list):
                latex_content += "\\textbf{選択肢:}\n\n"
                for j, choice in enumerate(choices):
                    escaped_choice = str(choice).replace("&", "\\&").replace("%", "\\%").replace("$", "\\$").replace("#", "\\#").replace("_", "\\_").replace("{", "\\{").replace("}", "\\}")
                    letter = chr(ord('A') + j)
                    latex_content += f"{letter}. {escaped_choice}\n\n"
                latex_content += "\n"
        
        # 正解の処理
        if answer:
            latex_content += f"\\textbf{{正解:}} {answer}\n\n"
        
        latex_content += "\\vspace{1em}\n\\hrule\n\\vspace{1em}\n\n"
    
    latex_content += r"""
\end{document}
"""
    
    return latex_content
