firebase_api_key = "AIzaSyCNqS0iUIG4UyZMTTFtCqTq7Pv-MNL0WuY"

[firebase_credentials]
type = "service_account"
project_id = "dent-ai-4d8d8"
private_key_id = "900fed7df5b2c797108626a8cfe3e3bedb9b74fa"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCcwfqqKDyf0SGc
t4Io0nXjp7ZH55CaTEELHP/gEKLKm0ZmP/BHFf3S/U5rfjmrJyal/iRaAnWhYo2y
TBm4cp7muw2qRUvfeyAUri8weiFoYY+Gi93HTYsAVwV0sqK2LK4wSXUxCNyXw6td
l7JLW6VRCj92EHdewwxT5OxEzlJ/KKTUTerTndlIeAvQLeaV1ToIYbOnvGsceG7s
FUWgNOTqvmGVbKJoFSwuidm0ON7Gf+tL02ng7jY0zm2kczFvNNA41RkHz8d8XRD+
2J4cgCtULsfiV2V7SXZgXqdGkbl4HuUfpZ0+Rl2RtIW8m2X/9r3CYu1IxmsEIofx
fJAhtsu9AgMBAAECggEAJbxam9io0240MbZJWotjfsSyUDfx6vr9U3ANNsK6dZyQ
g2/T50DnhAGffaf6uPVpS99Un+hkqc+APdItBOZu0ytnXDxnSeqpa+EMkhZscWS+
+Mw1vNMxaYkJUrDoE4PJAO3GDOJNvCkJ2TN548MxlkMpyMGpAsJgdteuetfSKzLc
fNvC8vYAoQ0J6edIBHhCk/A851HbwLBbuBJJVEwyNu+OUttVBsZ/dXd4Z67qFi3m
BmjHc+rbZTkkfwaabI3YWKaQ8oZdeghAcms6+qNoEFKxoDouZ7/NVyhRQQL+t33I
zF/rw2p0e9wRUBPrkUZ7z5RYc7dAFk5h7unCeK/tvwKBgQDSr+M1MAm3Msp44JtF
59pWwO5wnOv/Oz1x/DkDXjx0kQhBaNwn+YGW9gAIu/kHvRGi/6uvQPLFnDfhNRUu
6Lx6MUbARtDs9YsuZmW5rP6Hm99oNkxgF2q8pZJZlDZ6gEJTtpgZakWrX72TwWMZ
tq3NvzHGs6eD/orA3Cg1C8vPgwKBgQC+eNLrmN6tTwENePHOc3IpQN1+CInE8nxV
lZl2nqo1vNHLyeltNqzcOKD1JQN479dxseAO3Mtxw1hANzSCz4z0IlTaoXIguZCn
fsZ8U9FExBH5DDrQhlcX7RcNloHm/MlPdFniLkSjhWrj3JzWCAETjD98iL6d2MZ7
dEKv1IrTvwKBgBF8NXARl4zTs0gK4/gOQOmYQ3GnJFLfWL8f/p9P79aAvt2m1Tag
F2gu7FvNNeK1h0Qu0dHOoxdRWrXfEO3+tL2zXzrP5cD0s+Na7jBVsh4RCp58eyQy
bVJQr2+txEOwZ1DJQ6BAWJ3baUFc+FuG9K+xoXDrMgjbVCqjWtbkLrr/AoGAC0AZ
vT6/UF9NQZ12MuqQwK0LKCma8Z4dB/UZJm+CwD/R6IaZmhDTrwJNR42TIe6QvC90
e4xBHAwcx1Y7bMqTmcv5VRyaICK1z57mXGua/cPTB/HX+38j387qQKw2Kg2eWmoV
8Q0okrwLrz/Vp7K7VYtAKLvu/mXSe3JHihk0xgMCgYEArxSdgh5mmI2ST92XXx6g
Q6nIs8cr82gQu8WVsi7IOrX0bEhlu9fO2jvjxotqXfbxKcun7I9MHnS/ufVll1U/
5bSly36d/8/zWwRDUKoOIDkfc4NUspXPlE/KV4so3eVBNWDWhVuxN1VjPRT9K9UU
o90eMUpQgHUF9mHFEa+w3Oc=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@dent-ai-4d8d8.iam.gserviceaccount.com"
client_id = "105166723639216700554"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40dent-ai-4d8d8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Cookie暗号化用のパスワード（自動ログイン機能で使用）
cookie_password = "dental_ai_secure_cookie_key_2025_87d39f2e1b5c4a7f9e3d8c1a6b4e2f0d9c8b7a5e3f1d6c4b2a0e8f7d5c3b1a9e"

ga_api_secret = "m8iRAaV-R1Gts78QywVnpw"
ga_measurement_id = "G-712ZD4WRYQ"